### ISSUE TITLE
Populating workspace issue with spgo

### ISSUE THREAD

**Issue by RushikeshMEAN** [chrishasz/spgo#68]
I have followed all the steps as mentioned in documentation.

I have two SharePoint sites 
1) Personal account (onmicrosoft.com)
2)organisation account (user@company.com)

I am able to connect with first account (personal account) and loaded all data from server successfully.
But unable to load data from second site(organisation site). It just keep saying "populating  workspace" but nothing gets loaded. 

{
    "sourceDirectory": "src",
    "sharePointSiteUrl": "https://tenant.sharepoint.com/sites/sitename/Demo",
    "publishingScope": "SaveOnly",
    "authenticationType": "Digest",
    "storeCredentials" : true,
    "remoteFolders": [
        "/app"
    ]

}
Can you help me with this.

I am using VS Code Ver : 1.23.1 and SPGO ver : 1.3.2

**Comment by sg-chrishasz** [comment]
Hello @RushikeshMEAN - is the content you are trying to load from a folder (or library) called '`app`' at the root of the SharePoint web called `https://tenant.sharepoint.com/sites/sitename/Demo`, or are you looking to load data from the path '`Demo/app`' inside a SharePoint web at `https://tenant.sharepoint.com/sites/sitename`?

For the latter, I would recommend updating your spgo.json config to look like this:

``` json
{
"sourceDirectory": "src",
"sharePointSiteUrl": "https://tenant.sharepoint.com/sites/sitename",
"publishingScope": "SaveOnly",
"authenticationType": "Digest",
"storeCredentials" : true,
"remoteFolders": [
"demo/app/**/*"
]
}
```
_note: I added the glob notation for all files and folders ('**/*') to the remoteFolders node so that SPGo knows to get the entire contents of the folder._

if not, can you open SPGo and see if there are any log messages or errors in the SPGo output channel in VSCode?

**Comment by RushikeshMEAN** [comment]
Hi @sg-chrishasz ,

As you suggested , I tried with my another root site , there I have "app" folder with some files. 

https://tenant.sharepoint.com/sites/sitename

I am trying to load files from my "app" document library which is place at root site.

{
    "sourceDirectory": "src",
    "sharePointSiteUrl": "https://tenant.sharepoint.com/sites/sitename",
    "publishingScope": "SaveOnly",
    "authenticationType": "Digest",
    "storeCredentials": true,
    "remoteFolders": [
        "/app/**/*",
        "/SiteAssets/**/*.*",
        "/_catalogs/wp/",
        "/_catalogs/masterpage/"
    ]
}

Still facing the same issue, nothing gets populated.

Is there anything to do with authentication process ? Our client is using windows authentication to authenticate SharePoint site. My login credentials are in following format
Login Id : username@companyname.com
Password : windows password

I have checked output window also but nothing gets logged there.

**Comment by WKFS-InfoDevSupport** [comment]
Looking forward to the reply - I'm having an almost identical issue.

**Comment by kelmankenberg** [comment]
I am looking forward to the reply, as I have almost the exact issue.

**Comment by kelmankenberg** [comment]
I am looking forward to the reply, as I have almost the exact issue.

**Comment by sg-chrishasz** [comment]
Hello @RushikeshMEAN and @kelmankenberg 

Thanks for providing the error message. When I've seen this before, it is usually due to TCP configurations with your local host or network, which are causing the total download to timeout. Usually this is the case when you try to download too many files in parallel. I susupect that the total number of files in those libraries is greater than the number of files your host is able to download at once. A temporary workaround could be to use the [Retrieve Folder](https://docs.sitego.co/spgo/commands/retrieve-folder) command instead to populate each of those folders individually. Sorry I don't have a better answer at this time.

SPGo uses the [SPPull](https://github.com/koltyakov/sppull) library to download files. @koltyakov, do you have a way to serialize downloads with this library? Any other suggestions we should look into?

**Comment by koltyakov** [comment]
> Our client is using windows authentication to authenticate SharePoint 2013 (O365) site.

Didn't get is it SPO or 2013 OnPrem? Due to a mentioned sharePointSiteUrl value seems to be more likely SPO rather than 2013.

So, when it's SharePoint Online and the same account can download from one site collection but not another one, the things to check:

- Permissions (yeah, it's so obvious that not likely but is better to check)
- Are custom scripts enabled on the site collection (using O365 CLI `spo site classic set --url https://{tenant}.sharepoint.com/{site_uri} --noScriptSite false` or PoSH `Set-SPOSite -Identity https://{tenant}.sharepoint.com -DenyAddAndCustomizePages $False`)
- Check any proxy settings which is possibly used to access the the tenant

For standalone authentication troubleshooting, I'd suggest low level [approach](https://github.com/koltyakov/node-sp-auth-troubleshoot) to separate any authentication-related issues.

Using SPPull I download from time to time thousands of files, so do not think it's because of a number of files. Also, they are downloaded in a sequence queue not at once.

> do you have a way to serialize downloads with this library?

@sg-chrishasz can you elaborate a bit?

@kelmankenberg, can you also check if using this [basic low-level setup](https://github.com/koltyakov/sppull/blob/master/examples/basic/src/index.ts) you can or cannot download folder files from your site where you're facing the issue?

To minify troubleshooting setup [this generator](https://github.com/koltyakov/generator-sppp) can be used, once the project is scaffolded and connected to SharePoint `gulp pull` task should be triggered.

This could help with understanding what might be wrong. Thanks!

**Comment by sg-chrishasz** [comment]
@koltyakov thank you for the great advise!

When I googled the timeout error, I found a number of references to TCP networking in node. Issue roots were either related to timeouts from issuing too many parallel downloads at once (https://github.com/Azure/azure-storage-node/issues/343) or permissions as you called out above.

It is quite possible my rca was incorrect, in which case more details on the specific local environment or remote environment. the 23.100.72.38 IP address resolves to Microsoft, so I assume Office365.

@RushikeshMEAN you also say that you can connect with an @onmicrosoft.com account. Are you able to log in to SharePoint using your company account outside of SPGo? Does your company use any sort of 2FA or external auth provider?

**Comment by sg-chrishasz** [comment]
Adding this post from (Waldek's blog](https://blog.mastykarz.nl/econnreset-error-connecting-office-365-nodejs/) where he describes this problem as a known issue when accessing O365 apis from node. Sounds like there is an issue with TLS 1.2 and O365 certs.

**Comment by RushikeshMEAN** [comment]
@sg-chrishasz  and @koltyakov  , Yes  it is a SPO environment. It took a bit long to gather information about authentication process. Our client is using ADFS authentication. 

I have added 'authenticationDetails' as suggested in SPGO documentation. Still facing issue with connection. I have added bellow code
```
{
    "sourceDirectory": "src",
    "sharePointSiteUrl": "https://tenant.sharepoint.com/sites/sitename",
    "publishingScope": "SaveOnly",
    "authenticationType": "ADFS",
    "remoteFolders": [
        "/SiteAssets/**/*.*",
        "/_catalogs/wp/",
        "/_catalogs/masterpage/"
    ],
    "authenticationDetails": {
        "adfsUrl": "[
            http://abc.domain.com/adfs
        ]",
        "relyingParty": "[
            urn:federation:MicrosoftOnline
        ]"
    }
}
```
 
But after firing command 'Populate Local Workspace ' it showing me "Populating workspace" message on VS task bar. and in output window it says 
`Starting File Synchronization...`

But nothing gets populated or didn't ask me for further credential window. It just stuck there.
Correct me if I am missing something.

**Comment by chrishasz** [comment]
Hello @rushikeshMEAN

I found and fixed a bug with how ADFS data is loaded from `SPGo.json`. 

Can you confirm that you are still having this issue, otherwise I will close it in the next week.

**Comment by chrishasz** [comment]
Closing due to age.
