### ISSUE TITLE
When saving, using a Mac, the files are not updated on SharePoint.  There are no error messages and I have SaveOnly in the json config file

### ISSUE THREAD

**Issue by SiliconReef** [chrishasz/spgo#78]

**Comment by sg-chrishasz** [comment]
Hello @SiliconReef - Do the `PublishMajor` or `PublishMinor` also fail?

**Comment by SiliconReef** [comment]
Hi Chris,

We can do major and minor publishing with no problem, it is only when we save that the file doesn’t appear to save to SharePoint.  It saves on the local machine but does not push  the changes to the site collection.  Below is the config we are using:

{
    "checkInMessage" : "Updated by Silicon Reef",
    "sourceDirectory": "Source",
    "sharePointSiteUrl": "https://siliconreef.sharepoint.com/sites/ProjectTracker",
    "publishingScope": "SaveOnly",
    "authenticationType": "Digest",
    "storeCredentials": true,
    "remoteFolders": [
    "/Style Library/css/**/*.*",
    "/Style Library/js/**/*.*",
    "/Style Library/html/**/*.*",
    "/Style Library/fonts/**/*.*",
    "/Style Library/images/**/*.*"
    ]
}

Many thanks for your quick response

[cid:image002.png@01D4C840.D4F00970]

Adam Brown​

 |

Technical Director

 |

Silicon Reef Ltd


www.siliconreef.co.uk<https://goo.gl/HkLbTB>

 |

0333 9397976<tel:0333%209397976>

**Comment by sg-chrishasz** [comment]
It looks like you are using a Publishing site (my assumption based on the `Style Library` elements in your `remoteFolders` node.

Strict publishing sites will not allow the `saveOnly` style of upload and, depending on how the library permissions are set, you will likely need to check out the file before you can update the file with `publishMinor` or `publishMajor`. I'll add a note about this to the docs.

Can you try to check the file out (you can do this from VSCode by right-clicking on the file in the tree-view and selecting `SPGo: Check out the current file`) and then seeing if `saveOnly` works? Otherwise, as a workaround, I'd suggest using check-out and then `publishMinor` as the best way for your team to modify your SharePoint content - and as a bonus, SPGo will automatically diff any changes made by other team members if there is a file edit conflict. 


If this doesn't work, I'll need to try to replicate this with a publishing site locally which will likely take a couple days

**Comment by SiliconReef** [comment]
Hi Chris,

Thanks for the response.  We have done some tests and the issue only appears to affect our Mac user.  All developers using windows machines can save as the should.

We have got a workaround where we checkout and publish when we want to save to Sharepoint, its just the save only functionality that doesn’t work as expected.

Many thanks for your quick responses,

[cid:image002.png@01D4C90C.EA4C81A0]

Adam Brown​

 |

Technical Director

 |

Silicon Reef Ltd


www.siliconreef.co.uk<https://goo.gl/HkLbTB>

 |

0333 9397976<tel:0333%209397976>

**Comment by zrizzi** [comment]
I am seeing this issue running in VS Code on a mac.  It just seems to time out.  I tried checking the file out, but this is the only response i get.

[2019-07-11 14:13:03.998] [renderer1] [warning] UNRESPONSIVE extension host, 'SiteGo.spgo' took 99% of 5207.806ms, saved PROFILE here: '/var/folders/1l/_vvsp_8x3hd5gfw1gv9tt4hc0000gp/T/exthost-5da71e.cpuprofile' [{"id":"gc","total":65320,"percentage":1},{"id":"program","total":490,"percentage":0},{"id":"SiteGo.spgo","total":5141800,"percentage":99}]
[2019-07-11 15:26:55.485] [renderer1] [warning] UNRESPONSIVE extension host, 'SiteGo.spgo' took 99% of 5243.161ms, saved PROFILE here: '/var/folders/1l/_vvsp_8x3hd5gfw1gv9tt4hc0000gp/T/exthost-15471c.cpuprofile' [{"id":"gc","total":67351,"percentage":1},{"id":"program","total":242,"percentage":0},{"id":"SiteGo.spgo","total":5175502,"percentage":99}]
[2019-07-11 15:31:31.385] [renderer1] [warning] UNRESPONSIVE extension host, 'SiteGo.spgo' took 99% of 5216.995ms, saved PROFILE here: '/var/folders/1l/_vvsp_8x3hd5gfw1gv9tt4hc0000gp/T/exthost-703759.cpuprofile' [{"id":"gc","total":64590,"percentage":1},{"id":"program","total":510,"percentage":0},{"id":"SiteGo.spgo","total":5151707,"percentage":99}]

**Comment by chrishasz** [comment]
Closing as old.

Also, I tested the most recent version of SPGO on a Macbook Pro/OSX successfully.
