### ISSUE TITLE
[PR] Copy Absolute URL/Server Relative URL

### ISSUE THREAD

**Issue by CPritch** [chrishasz/spgo#86]
Hi @chrishasz ,

Again, fantastic extension for us transitioning. I have developed an extension that integrates with SPGo that adds two commands to copy the Abolute URL or the Server Relative url of a file or folder.

Currently it's a little hacky as I was not aware of how your extension was internally managing parameters/config.
I would love to submit a PR and integrate this feature if you think it's a feature you'd like in the extension? I'd rather not publish an extension dependent on yours.

**Comment by chrishasz** [comment]
Hello @CPritch,

That sounds like a great feature, and I would be honored if you wanted to contribute to SPGo! 

In terms of getting started, I would recommend reading the [build SPGo locally](https://www.chrishasz.com/spgo/development/build-locally).  

SPGo uses an asynchronous  architecture based on [promises](https://basarat.gitbooks.io/typescript/docs/promise.html) in order to prevent long-running commands from interfering with the editor. You can find an example of a simple command [here](https://github.com/chrishasz/spgo/blob/master/src/command/getCurrentFileInformation.ts)

To author the features, I prefer that you fork the repo, build the code, and then create a PR to merge from your fork into the main repo here. 

Please reach out with any questions!

**Comment by CPritch** [comment]
Hi @chrishasz 

Fantastic, I'm well versed in async/promise structure  and more than happy to adhere to any standards or design patterns established. I'll keep as close in structure to the current codebase as I can.

I'll get started on this OOH as soon as I can free up some time and be in touch with PR once done with the fork. Shouldn't take very long.
